import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'freshwater-fish', name: 'Freshwater Fish' },
  { id: 'saltwater-fish', name: 'Saltwater Fish' },
  { id: 'aquariums-tanks', name: 'Aquariums & Tanks' },
  { id: 'decorations', name: 'Decorations' },
  { id: 'filters-pumps', name: 'Filters & Pumps' },
  { id: 'food', name: 'Fish Food' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Neon Tetra',
    description: 'A vibrant and peaceful freshwater fish, perfect for community tanks.',
    price: 2.99,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'freshwater fish',
    category: 'freshwater-fish',
  },
  {
    id: '2',
    name: 'Clownfish',
    description: 'A popular and hardy saltwater fish, known for its bright orange color.',
    price: 19.99,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'clownfish saltwater',
    category: 'saltwater-fish',
  },
  {
    id: '3',
    name: '20-Gallon Aquarium Kit',
    description: 'A complete starter kit for any aspiring aquarist. Includes tank, filter, and heater.',
    price: 129.99,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'aquarium tank',
    category: 'aquariums-tanks',
  },
  {
    id: '4',
    name: 'Sunken Ship Decoration',
    description: 'A classic and adventurous decoration for any aquarium theme.',
    price: 15.49,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'aquarium decoration',
    category: 'decorations',
  },
  {
    id: '5',
    name: 'AquaClear Power Filter',
    description: 'A powerful and quiet hang-on-back filter for crystal clear water.',
    price: 34.99,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'aquarium filter',
    category: 'filters-pumps',
  },
  {
    id: '6',
    name: 'Tropical Fish Flakes',
    description: 'High-quality fish flakes for a balanced diet for your tropical fish.',
    price: 8.99,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'fish food',
    category: 'food',
  },
  {
    id: '7',
    name: 'Betta Fish',
    description: 'Known for their beautiful fins and vibrant colors, Betta fish are a stunning addition.',
    price: 7.50,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'betta fish',
    category: 'freshwater-fish',
  },
  {
    id: '8',
    name: 'Royal Gramma',
    description: 'A brightly colored and peaceful saltwater fish, with a purple front and yellow tail.',
    price: 24.99,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'saltwater fish',
    category: 'saltwater-fish',
  },
];
